Settings:
    Language:
        out_of_fuel: 'Dir ist der Treibstoff ausgegangen'
        use_jetpack: 'Wuuusch....'
        use_glider: 'Wie eine Wolke...'
        use_hook: ''
        destroy: 'Dein <item> ist dir zu bruch gegangen!'
Jetpack:
    Name: &eJetpack
    Lore:
    - &fRechtsklick zum anlegen.
    - &fDanach doppel sprung zum losfliegen!
    - '&7Durability: 100'
Glider:
    Name: &eGleiter
    Lore:
    - &fRechtsklick um zu Gleiten.
    - '&7Durability: 50'
Hook:
    Name: &eEnterhaken
    Lore:
    - &fRechtsklick um dich rüberzuschwingen.